version: "3.8"
services:
  db:
    image: postgres
    container_name: PatternsDatabase
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: PatternsAdminPanel
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: